import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v16-appRouter";
import { AuthProvider } from "@/contexts/AuthContext";
// import { ThemeProvider } from "@mui/material/styles";
// import theme from "@/lib/theme"; // Nhớ check lại đường dẫn file theme

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
            <body className="min-h-full flex flex-col">
                <AppRouterCacheProvider options={{ enableCssLayer: true }}>
                    <AuthProvider>
                        {/* <ThemeProvider theme={theme}>{children}</ThemeProvider> */}
                        {children}
                    </AuthProvider>
                </AppRouterCacheProvider>
            </body>
        </html>
    );
}
