export enum Permission {
  // AUTH
  AUTH_LOGIN = 'AUTH_LOGIN',
  AUTH_CHANGE_PASSWORD = 'AUTH_CHANGE_PASSWORD',

  // USER
  USER_VIEW = 'USER_VIEW',
  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',
  USER_IMPORT = 'USER_IMPORT',
  USER_EXPORT = 'USER_EXPORT',
  USER_TOGGLE_STATUS = 'USER_TOGGLE_STATUS',
  USER_RESET_PASSWORD = 'USER_RESET_PASSWORD',

  // BUSINESS
  BUSINESS_VIEW = 'BUSINESS_VIEW',
  BUSINESS_CREATE = 'BUSINESS_CREATE',
  BUSINESS_UPDATE = 'BUSINESS_UPDATE',
  BUSINESS_DELETE = 'BUSINESS_DELETE',
  BUSINESS_UPLOAD_FILE = 'BUSINESS_UPLOAD_FILE',
  BUSINESS_TOGGLE_STATUS = 'BUSINESS_TOGGLE_STATUS',
  BUSINESS_RESET_PASSWORD = 'BUSINESS_RESET_PASSWORD',

  // REPORT SỞ 
  REPORT_SO_VIEW = 'REPORT_SO_VIEW',
  REPORT_SO_DELETE = 'REPORT_SO_DELETE',

  // REPORT DOANH NGHIỆP
  REPORT_DN_VIEW = 'REPORT_DN_VIEW',
  REPORT_DN_CREATE = 'REPORT_DN_CREATE',
  REPORT_DN_UPDATE = 'REPORT_DN_UPDATE',
  REPORT_DN_EXPORT = 'REPORT_DN_EXPORT',
}
